import {
  CobieneLogoLarge,
  Inst1,
  Inst10,
  Inst11,
  Inst12,
  Inst13,
  Inst14,
  Inst15,
  Inst16,
  Inst17,
  Inst18,
  Inst19,
  Inst2,
  Inst20,
  Inst21,
  Inst22,
  Inst3,
  Inst4,
  Inst5,
  Inst6,
  Inst7,
  Inst8,
  Inst9,
  JaeAbout,
  JaeCarousel,
  JaeOthers,
} from "../images";
import { faFacebook, faWhatsapp } from "@fortawesome/free-brands-svg-icons";
import {
  faEnvelope,
  faGlobe,
  faMobile,
} from "@fortawesome/free-solid-svg-icons";

export const jaeConfig = {
  header: {
    name: "jae",
    title: "Jefatura de Apoyo Educativo",
    logoImg: CobieneLogoLarge,
    menuList: [
      { id: "about-us", name: "NOSOTROS" },
      { id: "schools", name: "COLEGIOS" },
    ],
  },
  main: {
    sectionCarousel: [
      {
        title: "JEFATURA DE APOYO EDUCATIVO",
        imgBackground: JaeCarousel,
        buttons: [
          {
            type: "primary",
            id: "about-us",
            title: "Nosotros",
          },
          {
            type: "secondary",
            id: "requirements",
            title: "Requisitos",
          },
        ],
      },
    ],
    sectionAbout: {
      title: "Nosotros",
      subTitle:
        "Planificamos y evaluamos, los procesos educativos e instrucción, en el Comando  de Educación y Doctrina del Ejército.",
      descriptions: [
        "Supervisar y controlar la ejecución de los programas educativos de las escuelas en el Comando de Educación y  Doctrina del Ejército, de conformidad a la normatividad vigente",
        "Proporcionar el soporte académico para las actividades a desarrollar por la Jefatura de Educación del Comando de Educación y Doctrina del Ejército, en lo concerniente a los recursos humanos, organización, logísticos y financieros.",
      ],
      images: [JaeAbout],
    },
    sectionOther: {
      title: "Otras por orden del CG del Ejército o del CG del COEDE.",
      images: [JaeOthers],
    },
    sectionSchoolsLima: {
      title: "Colegios de Lima",
      cards: [
        {
          image: Inst1,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "PEDRO RUIZ GALLO",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst2,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "Tte. Crl Alfredo Bonifaz",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst3,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "6005 GRAL EMILIO SOYER CABERO",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst4,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "CRL JOSE JOAQUIN INCLAN",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst5,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "JESUS NIÑO",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst6,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "LA ESPERANZA",
          title3: "CUNA - JARDIN",
          button: "",
        },
        {
          image: Inst7,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "MATELLINI",
          title3: "CUNA - JARDIN",
          button: "",
        },
        {
          image: Inst8,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "Primeros Pasos",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst9,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "Las Palmas",
          title3: "INICIAL",
          button: "",
        },
        {
          image: Inst10,
          title: "Institución educativa Publica de Gestión Privada",
          title2: "SANTA ISABEL",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst11,
          title: "Cuna",
          title2: "Corazon de Jesus",
          button: "",
        },
      ],
    },
    sectionProvinceSchools: {
      title: "Colegios de Provincia",
      cards: [
        {
          image: Inst14,
          title: "Institución Educativa",
          title2: "MCAL ANDRES AVELINO CACERES - TUMBES",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst20,
          title: "INSTITUCION EDUCATIVA PRIVADA",
          title2: "TTE MIGUEL CORTES - SULLANA",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst15,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "CRL JOSE JOAQUIN INCLAN - PIURA  ",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst22,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "40159  AREQUIPA” - AREQUIPA",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst13,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "ANDRES AVELINO CACERES - PUNO",
          title3: "INICIAL - PRIMARIA",
          button: "",
        },
        {
          image: Inst21,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "CRL FRANCISCO BOLONESI - CUZCO",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst16,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "NUESTROS HEROES DE LA GUERRA DEL PACIFICO - TACNA",
          title3: "INICIAL - PRIMARIA - SECUNDARIA",
          button: "",
        },
        {
          image: Inst12,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "ANDRES AVELINO CACERES - LOCUMBA",
          title3: "INICIAL - PRIMARIA",
          button: "",
        },
        {
          image: Inst12,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "CRL RAMON ZAVALA SUAREZ - LOCUMBA",
          title3: "INICIAL",
          button: "",
        },
        {
          image: Inst17,
          title: "Institución Educativa Publica de Gestión Privada",
          title2: "MCAL ANDRES AVELINO CACERES - Iquitos",
          title3: "INICIAL",
          button: "",
        },
        {
          image: Inst18,
          title: "Institución Educativa",
          title2: "TARAPACA - IQUITO",
          title3: "INICIAL - PRIMARIA",
          button: "",
        },
        {
          image: Inst19,
          title: "Institución Educativa",
          title2: "N° 169 MARIA MONTESSORI - IQUITOS",
          title3: "INICIAL",
          button: "",
        },
      ],
    },
  },
  sectionContact: {
    title: "CONTÁCTO",
    subtitle: "Estamos a su servicio, contáctanos",
    socialsRed: [
      {
        href: "https://api.whatsapp.com/send/?phone=+51941801827&text=Estoy+interesado+en+su+producto+%2F+servicio&app_absent=0",
        icon: faWhatsapp,
        name: "Whatsapp",
        phone: "941801827",
      },
      {
        href: "mailto:contactos@servitec-peru.com",
        icon: faEnvelope,
        name: "Email",
      },
      {
        href: "https://www.facebook.com/Servitec.chorrillos/",
        icon: faFacebook,
        name: "Facebook",
      },
      { href: "https://youtu.be/FNMfFy4iKvg", icon: faMobile, name: "Phone" },
      {
        href: "https://youtu.be/FNMfFy4iKvg",
        icon: faGlobe,
        name: "Direción",
      },
    ],
  },
  footer: {},
};
